### This is notebook for learning how to use computer to solve algebra problems.

In [3]:
import numpy as np
import math

### 第一章：多项式

* 多项式的表示

In [5]:
#由于需要用到sympy库，暂时跳过

### 第二章：行列式
### 第三章：线性方程组

* n阶行列式

In [6]:
#计算矩阵的秩、行列式、逆、迹，特征值和特征向量
a = np.array([[1,2,1],
             [1,1,10],
             [1,1,15]])
print(np.linalg.matrix_rank(a)) #返回矩阵的秩
print(np.linalg.det(a)) #返回矩阵的行列式
print(np.linalg.inv(a)) #返回矩阵的逆
print(a.diagonal()) #返回矩阵的对角线元素，也可以通过offset参数在主角线的上下偏移，获取偏移后的对角线元素。a.diagonal(offset=1)返回array([1.10])
print(a.trace()) #返回迹
eigenvalues ,eigenvectors= np.linalg.eig(a) #eigenvalues为特征值。eigenvectors为特征向量
print(eigenvalues)
print(eigenvectors)

3
-4.999999999999999
[[-1.   5.8 -3.8]
 [ 1.  -2.8  1.8]
 [ 0.  -0.2  0.2]]
[ 1  1 15]
17
[15.84400594  1.38401026 -0.2280162 ]
[[-0.1305644  -0.96916692  0.85693465]
 [-0.55996866 -0.23012485 -0.51493554]
 [-0.81816137  0.08807966 -0.02245855]]


* 解线性方程组

例如：

    2x + 3y = 5
    x   + 3y = 3 
    解得 x=2,y=1/3.

In [7]:
a=np.array([[2,3],[1,3]])   #系数矩阵
b=np.array([5,3]).T     #常数项列矩阵
x=np.linalg.solve(a,b)  #方程组的解
x

array([2.        , 0.33333333])

In [8]:
#线性方程组解的结构暂时跳过

### 第四章：矩阵

* 矩阵的运算

In [9]:
#点乘
#+-*/均为对应元素进行运算(需要是形状相同的矩阵)
a=np.array([[2,1,1],
            [3,1,0],
            [0,1,2]])
a*a

array([[4, 1, 1],
       [9, 1, 0],
       [0, 1, 4]])

In [10]:
#矩阵乘法
a=np.array([[2,1,1],
            [3,1,0],
            [0,1,2]])
np.dot(a,a)

array([[7, 4, 4],
       [9, 4, 3],
       [3, 3, 4]])